version: '3'
services:
  web:
    build: .
    command: mix phx.server
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    depends_on:
      - scrapper
  scrapper:
    image: selenium/standalone-firefox-debug
    ports:
      - "4444:4444"
      - "5900:5900"
    shm_size: 512M
